pipeline {
    agent any

    stages {
        stage('test') {
            steps {
                dir('ProyectoJenkins') {
                    sh 'mvn clean compile test'
                }
            }
        }

        stage('Build application') {
            steps {
                dir('ProyectoJenkins') {
                    sh 'mvn package'
                }
            }
        }

        stage('Pasamos a producción') {
            steps {
                echo 'Deploy realizado'
            }
        }
    }
}
